--
-- Tables
-- This file declares all tables in the atomic_crm schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

create schema if not exists atomic_crm;

create table atomic_crm.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table atomic_crm.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table atomic_crm.contact_notes (
    id bigint generated by default as identity (sequence name atomic_crm."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table atomic_crm.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint
);

create table atomic_crm.deal_notes (
    id bigint generated by default as identity (sequence name atomic_crm."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table atomic_crm.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__user_id on atomic_crm.sales using btree (user_id);

create table atomic_crm.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table atomic_crm.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table atomic_crm.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table atomic_crm.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table atomic_crm.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references atomic_crm.sales(id);

alter table atomic_crm.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references atomic_crm.companies(id) on update cascade on delete cascade;

alter table atomic_crm.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references atomic_crm.sales(id);

alter table atomic_crm.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references atomic_crm.contacts(id) on update cascade on delete cascade;

alter table atomic_crm.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references atomic_crm.sales(id) on update cascade on delete cascade;

alter table atomic_crm.deals
    add constraint deals_company_id_fkey foreign key (company_id) references atomic_crm.companies(id) on update cascade on delete cascade;

alter table atomic_crm.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references atomic_crm.sales(id);

alter table atomic_crm.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references atomic_crm.deals(id) on update cascade on delete cascade;

alter table atomic_crm.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references atomic_crm.sales(id);

alter table atomic_crm.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table atomic_crm.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references atomic_crm.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only atomic_crm.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only atomic_crm.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on atomic_crm.contact_notes using btree (contact_id);
create index contacts_company_id_idx on atomic_crm.contacts using btree (company_id);
create index deal_notes_deal_id_idx on atomic_crm.deal_notes using btree (deal_id);
create index deals_company_id_idx on atomic_crm.deals using btree (company_id);
